#! /bin/bash
#
# Script to build binary
#
# Usage:
#	sh build
# or
#	./build
SOURCE_DIR=`pwd`
VER=`cat dloadver`
DATE=`date -u +%Y-%m-%d`
TIME=`date -u +%H-%M-%S`
RELEASE=dload-${VER}-${DATE}-${TIME}
COPY_FILES_BINARY=" default \
	stage2/grldr stage2/grub.exe stage2/badgrub.exe stage2/grldr.mbr stage2/bootlace.com \
	stage2/hmload.com stage2/grldr.pbr stage2/grldr_cd.bin"

[ -z "$GRUB4DOS_TEMP" ] && GRUB4DOS_TEMP=./${RELEASE}-temp

#files=$(echo *)
files="GNUmakefile Makefile.am Makefile.in acinclude.m4 aclocal.m4 autogen.sh bootstrap.sh build compile config.guess config.h.in config.sub configure configure.ac default depcomp dloadver install-sh ldscript preset_menu.lst stage2"
if ! [ -d ${GRUB4DOS_TEMP} ] ; then
	mkdir ${GRUB4DOS_TEMP} || exit $?
fi
echo "WARNING!!! DO NOT USE THIS SOURCE TREE!!! THIS IS A TEMPORARY TREE, USE A PROPER SOURCE TREE INSTEAD." > ${GRUB4DOS_TEMP}/README
cp -a $files ${GRUB4DOS_TEMP} || exit $?

cd ${GRUB4DOS_TEMP} || exit $?

#############################################
#	     Build DLOAD proper
#############################################

./configure --enable-preset-menu=preset_menu.lst || exit $?
make clean
make || exit $?
mkdir ${RELEASE} || exit $?
[ -f stage2/eltorito.sys ] && cp stage2/eltorito.sys ${RELEASE}
cp $COPY_FILES_BINARY ${RELEASE} || exit $?
cd ${RELEASE}
cd ..

#############################################
#		  POSTBUILD
#    Manage files, copy to release, ect.
#############################################

cd $SOURCE_DIR
if [ -d ipxe ] ; then
	cd ipxe/src
	[ -d .git ] && git pull
	make bin/undionly.kpxe EMBED=$SOURCE_DIR/ipxegrldr.ipxe,${GRUB4DOS_TEMP}/${RELEASE}/grldr && cp -af bin/undionly.kpxe ${GRUB4DOS_TEMP}/${RELEASE}/ipxegrldr
	cd $SOURCE_DIR
fi

mkdir ${RELEASE}
cp -rfv ${GRUB4DOS_TEMP}/${RELEASE}/* ${RELEASE}/

