#! /bin/sh
#
# Script to build binary 
#
# Usage:
#	sh build
# or
#	./build
SOURCE_DIR=`pwd`
VER=`cat dloadver`
DATE=`date -u +%Y-%m-%d`
TIME=`date -u +%H-%M-%S`
RELEASE=dload-${VER}-${DATE}-${TIME}

#COPY_FILES="COPYING README_GRUB4DOS*.txt ChangeLog_*.txt \
#	config.sys default menu.lst grub.pif config.h\
#	stage2/pre_stage2.exec"

[ -z "$GRUB4DOS_TEMP" ] && GRUB4DOS_TEMP=./${RELEASE}-temp
	
files=$(echo *)
if ! [ -d ${GRUB4DOS_TEMP} ] ; then
	mkdir ${GRUB4DOS_TEMP} || exit $?
fi
cp -a $files ${GRUB4DOS_TEMP} || exit $?

cd ${GRUB4DOS_TEMP} || exit $?

#**********************************************
#	    compile BOOTX64.EFI
#**********************************************
./configure && make clean && make

mkdir x86_64-efi
cp stage2/pre_stage2.exec ./x86_64-efi/kernel.img
platform=`uname -m`
if [ $platform = 'x86_64' ]
then
    $SOURCE_DIR/mkimage -d ./x86_64-efi -p /efi/grub -o BOOTX64.EFI -O x86_64-efi -c preset_menu.lst
else
    $SOURCE_DIR/mkimage.i386 -d ./x86_64-efi -p /efi/grub -o BOOTX64.EFI -O x86_64-efi -c preset_menu.lst
fi

#**********************************************
#	   compile BOOTIA32.EFI
#**********************************************
mv stage2/Makefile.in stage2/Makefile.in-64
mv stage2/Makefile.in-i386 stage2/Makefile.in

./configure && make clean && make

mkdir ./i386-efi
cp stage2/pre_stage2.exec ./i386-efi/kernel.img
if [ $platform = 'x86_64' ]
then
    $SOURCE_DIR/mkimage -d ./i386-efi -p /efi/grub -o BOOTIA32.EFI -O i386-efi -c preset_menu.lst
else
    $SOURCE_DIR/mkimage.i386 -d ./i386-efi -p /efi/grub -o BOOTIA32.EFI -O i386-efi -c preset_menu.lst
fi

cd $SOURCE_DIR

mkdir $RELEASE

#rm -f ${RELEASE}.zip ${RELEASE}.rar ${RELEASE}.tar.gz || exit $?
#if ! 7z a ${RELEASE}.7z ${GRUB4DOS_TEMP}/BOOTX64.EFI ${GRUB4DOS_TEMP}/BOOTIA32.EFI $SOURCE_DIR/ChangeLog_UEFI.txt \
#    $SOURCE_DIR/menu.lst  $SOURCE_DIR/default ${GRUB4DOS_TEMP}/Get_Source_of_This_Build.txt ${GRUB4DOS_TEMP}/grub4dos_${CURR_REVISION}.diff \
#    ${GRUB4DOS_TEMP}/i386-efi ${GRUB4DOS_TEMP}/x86_64-efi mkimage.exe; then
#	echo 7z failed. Continue with zip or tar...
#fi

cp $GRUB4DOS_TEMP/BOOTIA32.EFI $RELEASE/
cp $GRUB4DOS_TEMP/BOOTX64.EFI $RELEASE/
