#! /bin/sh
#
# Script to build binary 
#
# Usage:
#	sh build
# or
#	./build
SOURCE_DIR=`pwd`
VER=`cat dloadver`
DATE=`date -u +%Y-%m-%d`
TIME=`date -u +%H-%M-%S`
RELEASE=dload-${VER}-${DATE}-${TIME}

[ -z "$GRUB4DOS_TEMP" ] && GRUB4DOS_TEMP=./${RELEASE}-temp
	
#files=$(echo *)
files="acinclude.m4 aclocal.m4 autogen.sh bootstrap.sh build compile config.guess config.h.in config.sub configure configure.ac COPYING default depcomp dloadver GNUmakefile install-sh ldscript Makefile.am Makefile.in mkimage mkimage.exe mkimage.i386 preset_menu.lst stage2"
if ! [ -d ${GRUB4DOS_TEMP} ] ; then
	mkdir ${GRUB4DOS_TEMP} || exit $?
fi
cp -a $files ${GRUB4DOS_TEMP} || exit $?

cd ${GRUB4DOS_TEMP} || exit $?

#**********************************************
#	    compile BOOTX64.EFI
#**********************************************
./configure && make clean && make

mkdir x86_64-efi
cp stage2/pre_stage2.exec ./x86_64-efi/kernel.img
platform=`uname -m`
if [ $platform = 'x86_64' ]
then
    $SOURCE_DIR/mkimage -d ./x86_64-efi -p /efi/grub -o BOOTX64.EFI -O x86_64-efi -c preset_menu.lst
else
    $SOURCE_DIR/mkimage.i386 -d ./x86_64-efi -p /efi/grub -o BOOTX64.EFI -O x86_64-efi -c preset_menu.lst
fi

#**********************************************
#	   compile BOOTIA32.EFI
#**********************************************
mv stage2/Makefile.in stage2/Makefile.in-64
mv stage2/Makefile.in-i386 stage2/Makefile.in

./configure && make clean && make

mkdir ./i386-efi
cp stage2/pre_stage2.exec ./i386-efi/kernel.img
if [ $platform = 'x86_64' ]
then
    $SOURCE_DIR/mkimage -d ./i386-efi -p /efi/grub -o BOOTIA32.EFI -O i386-efi -c preset_menu.lst
else
    $SOURCE_DIR/mkimage.i386 -d ./i386-efi -p /efi/grub -o BOOTIA32.EFI -O i386-efi -c preset_menu.lst
fi

cd $SOURCE_DIR

mkdir $RELEASE

cp $GRUB4DOS_TEMP/*.EFI $RELEASE/
